# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: tobylai-toby/kernel_build_action@patch-1
      with:
          kernel-url: https://github.com/LineageOS/android_kernel_xiaomi_sm8250
          kernel-dir: msm-4.19
          kernel-branch: lineage-21
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          android-version: 14
          aosp-clang-version: r487747c
          python-27: true
          disable-lto: true
          anykernel3: true
